version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run:
        name: Fastbuild amd64 release
        command: |
          bash build/run.sh make cross KUBE_FASTBUILD=true ARCH=amd64
    - run:
        environment:
          REGISTRY: quay.io/giantswarm
        name: Build docker container
        command: |
          cd cluster/images/hyperkube/
          export VERSION=v1.11.1-$CIRCLE_SHA1-giantswarm
          make build ARCH=amd64
          docker tag $REGISTRY/hyperkube-amd64:$VERSION $REGISTRY/hyperkube:$VERSION
    - deploy:
        environment:
          REGISTRY: quay.io/giantswarm
        name: Deploy (if branch == "v1.11-giantswarm")
        command: |
          if [ "${CIRCLE_BRANCH}" == "v1.11-giantswarm" ]; then
              echo -n "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" quay.io/giantswarm
              docker push $REGISTRY/hyperkube:v1.11.1-$CIRCLE_SHA1-giantswarm
          fi
